### PR TITLE
Fix theme parsing bug

### LINKED ISSUE #112: ThemeCommand accepts all arguments -bg flag
Screenshot 2024-03-28 at 2 06 26 PM
Shown above: Dook will display theme updated to user even if theme does not exist.

### PR DESCRIPTION
**Pull request by jerremyng**
Fixes #112

Dook accepts all -bg arguments for the theme command even when theme does not exit.

This commit fixes it and will instead display a theme not found message (see below).
Screenshot 2024-03-28 at 2 39 53 PM

Also note that theme commands are now:
`theme -bg dark` and `theme -bg light` (dark and light are non-case sensitive)

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ThemeCommandParser.java [hunk 1]
```diff
@@ -31,7 +31,18 @@ public ThemeCommand parse(String args) throws ParseException {
         }
         argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_THEME);
 
-        Theme theme = ParserUtil.parseTheme(argMultimap.getValue(PREFIX_THEME).get());
+        Theme theme;
```
Comment (cyqjoseph) [inline src/main/java/seedu/address/logic/parser/ThemeCommandParser.java:34]: Good fix!

**Review by cyqjoseph — COMMENTED** [review]
LGTM!

File: src/main/java/seedu/address/commons/core/Theme.java
Comment (gauravuj) [inline src/main/java/seedu/address/commons/core/Theme.java:1]: Great fix! Makes it easy for others to add more themes

File: src/test/java/seedu/address/model/ModelManagerTest.java [hunk 2]
```diff
@@ -39,7 +39,7 @@ public void setUserPrefs_nullUserPrefs_throwsNullPointerException() {
     public void setUserPrefs_validUserPrefs_copiesUserPrefs() {
         UserPrefs userPrefs = new UserPrefs();
         userPrefs.setAddressBookFilePath(Paths.get("address/book/file/path"));
-        userPrefs.setGuiSettings(new GuiSettings((double) 1000, (double) 500, 300, 100, "DARKTHEME"));
+        userPrefs.setGuiSettings(new GuiSettings((double) 1000, (double) 500, 300, 100, "DARK"));
```
Comment (gauravuj) [inline src/test/java/seedu/address/model/ModelManagerTest.java:42]: Good job on fixing the test cases as well +1
