### PR TITLE
Fix ProfCommand bug

### LINKED ISSUE #135: Prof json file fetching fails on jar file
Prof command no work

### PR DESCRIPTION
**Pull request by jerremyng**
Closes #135

### CODE REVIEW

File: src/main/java/seedu/address/storage/JsonProfDataStorage.java [hunk 1]
```diff
@@ -59,9 +61,19 @@ public Optional<ReadOnlyAddressBook> readProfData() throws DataLoadingException
      */
     public Optional<ReadOnlyAddressBook> readProfData(Path filePath) throws DataLoadingException {
         requireNonNull(filePath);
-        // issue
-        Optional<JsonSerializableProfData> jsonProfData = JsonUtil.readJsonFile(
-                Paths.get(this.getClass().getResource(filePath.toString()).getPath()), JsonSerializableProfData.class);
+
+        Optional<JsonSerializableProfData> jsonProfData;
```
Comment (ChrysanthemumT) [inline src/main/java/seedu/address/storage/JsonProfDataStorage.java:65]: you are amazing! looks great

**Review by ChrysanthemumT — APPROVED** [review]
looks good, thanks for fixing
