### PR TITLE
Fixes editing related bugs

### LINKED ISSUE #150: [PE-D][Tester D] Error message for adding entire list of prof
## Steps to replicate 

1. Add one prof, e.g. `prof -n aaron`.

2. Add all prof with `prof -a`.

## Expected

Success message.

## Actual

Error message.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: shunjieee/ped#2

### LINKED ISSUE #160: [PE-D][Tester E] Error message could be better
Just a nit, entered edit 1 and got At least one field to edit must be provided. for the empty contact list. May be better to display an error message that says contact list is empty so no changes can be made

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: xinen26/ped#8

### LINKED ISSUE #162: [PE-D][Tester E] Minor glitch in UI
I tried pressing /<- button and it could actually allow my cursor to go behind the /> on the command line prompt and when i try to enter a command, the />  gets copied into my command

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: xinen26/ped#9

### PR DESCRIPTION
**Pull request by jerremyng**
1. Closes #160 
* The commit fixes the order of error checks so that the correct invalid index error can be thrown first

2. Closes #150 
* Was from the previous commit that was reverted. Fixes bug when editing person without actually making any different changes

3. Closes #162 
* Dook will place the cursor behind the `> ` in the command box and that is incorrect behaviour.
* Lets correct that to place it after the '> '.

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Address.java [hunk 1]
```diff
@@ -52,7 +52,13 @@ public boolean equals(Object other) {
         }
 
         Address otherAddress = (Address) other;
-        return value.equals(otherAddress.value);
+        if (this.value == null && otherAddress.value == null) {
```
Comment (cyqjoseph) [inline src/main/java/seedu/address/model/person/Address.java:55]: Nice!

File: src/main/java/seedu/address/ui/CommandBox.java [hunk 2]
```diff
@@ -51,6 +51,14 @@ public CommandBox(CommandExecutor commandExecutor) {
...
         });
 
+        commandTextField.setOnKeyPressed(event -> {
+            if (event.getCode() == KeyCode.UP) {
+                // Move the caret to the beginning of the text
+                commandTextField.positionCaret(2);
+                event.consume(); // Consume the event to prevent default behavior
+            }
+        });
+
```
Comment (cyqjoseph) [inline src/main/java/seedu/address/ui/CommandBox.java:61]: Great fix here, no more buggy UI behavior now

**Review by cyqjoseph — APPROVED** [review]
Overall LGTM!
